### ISSUE TITLE
Installation for Python version 3.11

### ISSUE THREAD

**Issue by nik-maheshwari** [BiomedSciAI/causallib#61]
Hi. I am trying to install this library in a Python 3.11 environment. I get the following error - 
```
ERROR: Could not find a version that satisfies the requirement causallib (from versions: none)
ERROR: No matching distribution found for causallib
```
However, it works for Python 3.9. Are there plans to update the library to be available for Python 3.11?

Thanks.

**Comment by ehudkr** [comment]
Hi, thanks for bringing this to my attention. 
This is indeed strange. I mean, I do test up to Python 3.9 and the PyPI signifier says Python::3.9, but this in and of itself shouldn't block the ability to install causallib on higher Python version.
I also don't seem to be able to replicate this. When I run
```bash
conda create -n test_causallib_install_with_py311 python=3.11
conda activate test_causallib_install_with_py311
pip install causallib
```
I get `Successfully installed causallib-0.9.5`.

Could you please provide more details so I can try to figure out from where this incompatibility arises?

**Comment by ehudkr** [comment]
Yes, the `<2` is a guard against non backward-compatible changes in the API when increasing a major version.
From some spare-time fiddling, there doesn't seem to be anything blocking causallib from working with pandas>2, but I haven't formally tested it yet. 

If that's the cause of your problems, there might be an annoying workaround in the meantime to manually install causallib's other dependencies (sklearn, matplotlib, etc.), and then install causallib while forcing pip not to install its dependencies: `pip install --no-deps causallib` (see [pip documentation](https://pip.pypa.io/en/stable/cli/pip_install/#options)).

**Comment by ehudkr** [comment]
Pandas >2 is now officially supported, and tests pass on Python 3.11
https://github.com/BiomedSciAI/causallib/pull/65
