### ISSUE TITLE
IPW computation

### ISSUE THREAD

**Issue by winston-zillow** [BiomedSciAI/causallib#66]
Briefly read the codes around IPW, in particular [this line](https://github.com/BiomedSciAI/causallib/blob/d80e3eaaad68ff72db370b08ea7098429ddae064/causallib/estimation/ipw.py#L131):

```python
# weight_matrix = 1.0 / probabilities
weight_matrix = probabilities.rdiv(1.0)
```
My understanding of [IPW](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3144483/) is that outcomes are weighted by: $w_i = \frac{a_i}{e_i} + \frac{(1 - a_i)}{(1 - e_i)}$. do I miss something or this is a bug?

**Comment by ehudkr** [comment]
To justify this further. There are other small benefits to this implementation that I have yet to seize.
For example, generalizing the average treatment effect on the treated/controls (ATT/ATC) to any arbitrary treatment level `v` can be simply done by multiplying the inverse probability matrix (`weight_matrix`) by the corresponding probability column: `weight_matrix *= probabilities[v]`. Then the column corresponding to `v` is all ones ($p_{i,v}$ times its inverse) and all the rest of the columns are the odds with respect to `v`. 

I hope this gives better context to the design decisions.

**Comment by winston-zillow** [comment]
I see. You turn the binary one-class label to a multi-class label first. That works. Thanks.
