### ISSUE TITLE
Causal Inference Benchmarks

### ISSUE THREAD

**Issue by Giovannibriglia** [BiomedSciAI/causallib#74]
Hi, thank you for your incredible work.

Do you know some public and easy-to-use causal inference benchmarks?

Thank you.

**Comment by ehudkr** [comment]
Hi, assuming you mean synthetic benchmarks, where ground truth (counterfactuals) is also known, there are several classic ones off the top of my head, like
* Twins: https://github.com/AMLab-Amsterdam/CEVAE/tree/master/datasets/TWINS
* IDHP: https://www.kaggle.com/datasets/konradb/ihdp-data
* ACIC 2016l https://jenniferhill7.wixsite.com/acic-2016/competition
* The Data Challenge in the Atlantic/American Causal Inference Conference is genrealy a great resource, for example:
   * ACIC 2017: https://github.com/vdorie/aciccomp/tree/master/2017
   * ACIC 2018: https://www.synapse.org/Synapse:syn11294478/wiki/494269
   * ACIC 2022: https://acic2022.mathematica.org/data
* RealCause organizes some of the above: https://github.com/bradyneal/realcause
* News: http://www.fredjo.com/files/NEWS_csv.zip

**Comment by Giovannibriglia** [comment]
Niceee, thank you so much for this feedback :)
